fix: Bundle lodash
I was getting this error within Local core's log:

```
Error: Cannot find module 'lodash'
Require stack:
- %%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js
- %%userDataPath%%/addons/local-addon-notes/lib/Notes.js
- %%userDataPath%%/addons/local-addon-notes/lib/renderer.js
- %%appPath%%/renderer/_browserWindows/app/app.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.o._resolveFilename (electron/js2c/renderer_init.js:33:1118)
    at Function.n._resolveFilename (file://%%appPath%%/renderer/_browserWindows/app/app.js:2:432204)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.6517 (%%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js:1:324038)
    at n (%%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js:1:324857)
    at Object.8038 (%%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js:1:322772)
    at n (%%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js:1:324857)
    at Object.9667 (%%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js:1:282129)
    at n (%%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js:1:324857)
    at Object.3607 (%%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js:1:321360)
    at n (%%userDataPath%%/addons/local-addon-notes/node_modules/@getflywheel/local-components/dist/index.js:1:324857)
```